// Minimal static file server for the Listing Scraper frontend.
// Serves files from ./public on PORT (default 3000) on HOST 0.0.0.0.
// Also serves a virtual /config.js endpoint that exposes the public Clerk key.
const http = require('http');
const fs = require('fs');
const path = require('path');

// Load /app/frontend/.env (best-effort; we only need a couple of keys here)
try {
  const envPath = path.join(__dirname, '.env');
  const envText = fs.readFileSync(envPath, 'utf8');
  envText.split(/\r?\n/).forEach(function (line) {
    var m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !process.env[m[1]]) {
      var v = m[2];
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      process.env[m[1]] = v;
    }
  });
} catch (e) { /* no .env, ignore */ }

const ROOT = path.join(__dirname, 'public');
const PORT = parseInt(process.env.PORT || '3000', 10);
const HOST = process.env.HOST || '0.0.0.0';

// If CLERK_PUBLISHABLE_KEY is supplied via env, write/overwrite the static
// /config.js file so the in-browser key matches the env value. This makes
// runtime overrides possible on the preview environment without manually
// editing public/config.js. On production deployments where env vars aren't
// set, the bundled public/config.js is used as-is.
try {
  const pk = process.env.CLERK_PUBLISHABLE_KEY;
  if (pk) {
    const cfgPath = path.join(ROOT, 'config.js');
    const body = '/* Generated by static-server.js from env at startup. */\n'
      + 'window.__APP_CONFIG__ = '
      + JSON.stringify({ clerkPublishableKey: pk })
      + ';\n';
    fs.writeFileSync(cfgPath, body, 'utf8');
    console.log('Wrote ' + cfgPath + ' from CLERK_PUBLISHABLE_KEY env');
  }
} catch (e) {
  console.warn('Could not write public/config.js from env:', e && e.message);
}

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain; charset=utf-8',
};

function send(res, code, body, headers = {}) {
  res.writeHead(code, headers);
  res.end(body);
}

const server = http.createServer((req, res) => {
  try {
    let url = decodeURIComponent((req.url || '/').split('?')[0]);
    if (url === '/') url = '/index.html';
    const safe = path.normalize(url).replace(/^([\/\\]\.\.)+/, '');
    const filePath = path.join(ROOT, safe);
    if (!filePath.startsWith(ROOT)) {
      return send(res, 403, 'Forbidden');
    }
    fs.stat(filePath, (err, stat) => {
      if (err || !stat.isFile()) {
        // Fallback to index.html for SPA-like behavior
        const fallback = path.join(ROOT, 'index.html');
        return fs.readFile(fallback, (e2, data) => {
          if (e2) return send(res, 404, 'Not Found');
          send(res, 200, data, { 'Content-Type': 'text/html; charset=utf-8' });
        });
      }
      const ext = path.extname(filePath).toLowerCase();
      const type = TYPES[ext] || 'application/octet-stream';
      fs.readFile(filePath, (e3, data) => {
        if (e3) return send(res, 500, 'Read error');
        send(res, 200, data, { 'Content-Type': type, 'Cache-Control': 'no-store' });
      });
    });
  } catch (e) {
    send(res, 500, 'Server error');
  }
});

server.listen(PORT, HOST, () => {
  console.log(`Static server on http://${HOST}:${PORT}, serving ${ROOT}`);
});
